# RAG System Configuration - Korrigierte Struktur

# =============================================================================
# APPLICATION
# =============================================================================
application:
  name: "RAG Industrial Chatbot"
  version: "4.0.5"
  description: "Service-orientierte RAG-Architektur"
  environment: "development"
  debug_mode: true

# =============================================================================
# LLM CONFIGURATION
# =============================================================================
llm:
  providers: ["ollama"]
  model_name: "llama3.1:8b"
  base_url: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 2048
  timeout: 60
  retry_attempts: 3
  fallback_models: ["llama3.1:8b", "llama2:7b"]

# =============================================================================
# EMBEDDING CONFIGURATION
# =============================================================================
embeddings:
  providers: ["ollama"]
  model_name: "nomic-embed-text"
  base_url: "http://localhost:11434"
  dimensions: 768
  batch_size: 16
  cache_size: 1000
  cache_embeddings: true
  max_retries: 3
  fallback_models: ["nomic-embed-text", "mxbai-embed-large"]

# =============================================================================
# VECTOR STORE CONFIGURATION
# =============================================================================
vector_store:
  providers: ["chroma"]
  persist_directory: "./data/vectorstore"
  collection_name: "industrial_documents"
  distance_metric: "cosine"
  chroma:
    host: "localhost"
    port: 8000
    ssl: false
    headers: {}

# =============================================================================
# TEXT PROCESSING
# =============================================================================
text_processing:
  chunk_size: 800
  chunk_overlap: 150
  separators: ["\n\n# ", "\n\n## ", "\n\n### ", "\n\n", "\n", ". "]
  min_chunk_size: 100
  max_chunk_size: 2000
  enable_preprocessing: true
  remove_whitespace: true
  normalize_unicode: true
  filter_empty_chunks: true

# =============================================================================
# LOGGING
# =============================================================================
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./data/logs/rag_system.log"
  max_file_size: 10485760
  backup_count: 5
  json_format: false