# RAG Industrial - Hauptkonfiguration
# Service-orientierte Architektur v5.0.0

application:
  name: "RAG Industrial Chatbot"
  version: "5.0.0"
  description: "Service-orientierte RAG-Architektur für industrielle Dokumentenanalyse"
  environment: "development"  # development, staging, production
  debug_mode: true

# LLM-Konfiguration
llm:
  provider: "ollama"
  model_name: "llama3.1:8b"
  base_url: "http://localhost:11434"
  temperature: 0.1
  max_tokens: 2048
  timeout: 60
  retry_attempts: 3
  
  # Fallback-Modelle
  fallback_models:
    - "llama3.1:8b"
    - "llama2:7b"
    - "mistral:7b"

# Embedding-Konfiguration  
embeddings:
  provider: "ollama"
  model_name: "nomic-embed-text"
  base_url: "http://localhost:11434"
  dimensions: 768
  batch_size: 16
  cache_embeddings: true
  max_retries: 3
  
  # Fallback-Modelle
  fallback_models:
    - "nomic-embed-text"
    - "mxbai-embed-large"
    - "snowflake-arctic-embed"

# Vector Store Konfiguration
vector_store:
  provider: "chroma"
  persist_directory: "./data/vectorstore"
  collection_name: "industrial_documents"
  distance_metric: "cosine"
  
  # ChromaDB-spezifische Einstellungen
  chroma:
    host: "localhost"
    port: 8000
    ssl: false
    headers: {}

# Text-Processing Konfiguration
text_processing:
  chunk_size: 800
  chunk_overlap: 150
  separators:
    - "\n\n# "      # Hauptüberschriften
    - "\n\n## "     # Unterüberschriften  
    - "\n\n### "    # Sub-Überschriften
    - "\n\n"        # Absätze
    - "\n"          # Zeilenumbrüche
    - ". "          # Sätze
    - " "           # Wörter
    - ""            # Zeichen
  
  # Content-Klassifizierung
  content_types:
    - "step_by_step_guide"
    - "demo_instructions"
    - "installation_guide"
    - "technical_specifications"
    - "troubleshooting"
    - "general"

# Retrieval-Konfiguration
retrieval:
  k: 5
  enable_hybrid_search: true
  search_types:
    - "vector"
    - "keyword" 
    - "structure"
  
  # Gewichtung für Hybrid-Search
  weights:
    vector_score: 0.4
    keyword_score: 0.3
    structure_score: 0.3

# Session Management
session:
  timeout_minutes: 30
  max_sessions: 100
  cleanup_interval_minutes: 10
  persist_chat_history: true

# File Upload
file_upload:
  max_file_size_mb: 50
  allowed_extensions:
    - "pdf"
    - "txt"
    - "md"
    - "docx"
  upload_directory: "./data/uploads"

# Cache-Konfiguration
cache:
  enable_embedding_cache: true
  cache_directory: "./data/cache"
  max_cache_size_gb: 2
  cache_ttl_hours: 24

# Monitoring & Health Checks
monitoring:
  enable_health_checks: true
  health_check_interval_seconds: 30
  enable_metrics: true
  metrics_port: 9090
  
  # Performance-Monitoring
  performance:
    track_response_times: true
    track_token_usage: true
    track_embedding_operations: true

# API-Konfiguration (für Phase 5)
api:
  enabled: false
  host: "0.0.0.0"
  port: 8080
  workers: 4
  cors_origins:
    - "http://localhost"
    - "http://localhost:3000"
    - "http://localhost:8501"

# Sicherheit
security:
  enable_api_key: false
  api_key_header: "X-API-Key"
  rate_limiting:
    enabled: false
    requests_per_minute: 60

# Entwicklung & Debug
development:
  auto_reload: true
  show_debug_info: true
  enable_profiling: false
  log_sql_queries: false